all:
  propel:
    class:      sfPropelDatabase
    param:
      phptype:  mysql
      host:     localhost
      database: itbhu
      username: root
      password: neev
  v2bb:
    class:      sfPropelDatabase
    param:
      phptype:  mysql
      host:     localhost
      database: v2bb
      username: root
      password: neev
