# default values
all:
  pager:
    homepage_max: 10
  web:
    name: itbhuglobal.org 
  mail:
    server_type: smtp
    hostname:    
    username:    
    password:    
    character:   utf-8
  from: 
    mail: system@itbhuglobal.org
    name: ITBHUGlobal org Administrator
  to:
    adminmail: gourishanker@neevtech.com
  lor:
    location: 1
    employer: 2
    position: 3
    linkedin: 4
    general: 5
    email: 6