# default values
all:
  pager:
    homepage_max: 10
  web:
    name: itbhuglobal.org 
  mail:
    server_type: smtp
    hostname:    neevtech.com
    username:    neev-smtp
    password:    sp2Enu
    character:   utf-8
  from: 
    mail: system@itbhuglobal.org
    name: ITBHUGlobal org Administrator
  to:
    adminmail: gourishanker@neevtech.com