default:
  http_metas:
    content-type: text/html

  metas:
    title:        ITBHU Global
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [itbhu, typo, globalmenu]

  javascripts:    [itbhu, prototype]

  has_layout:     on
  layout:         layout
