all: 
 is_secure: on
 credentials: [[admin, user]]
forgotpassword:
 is_secure: off
forgotpasswordform:
 is_secure: off
composemail:
 is_secure: off
lorform:
 is_secure: off
lor:
 is_secure: off
lorsubmit:
 is_secure: off
invite:
 is_secure: off