# default values
all:
  pager:
    homepage_max: 10
  web:
    name: itbhuglobal.org 
  mail:
    server_type: smtp
    hostname:    
    username:    
    password:    
    character:   utf-8
  from: 
    mail: system@itbhuglobal.org
    name: ITBHUGlobal org Administrator
  to:
    adminmail: gourishanker@neevtech.com