# default values
all:
  pager:
    homepage_max: 10
  web:
    name: itbhuglobal.org 
  mail:
    server_type: smtp
    hostname:    192.168.1.84
    username:    neev@smtp.neevtech.com
    password:    sp2English
    character:   utf-8
  from: 
    mail: system@itbhuglobal.org
    name: ITBHUGlobal org Administrator
  to:
    adminmail: gourishanker@neevtech.com
  lor:
    location: 1
    employer: 2
    position: 3
    linkedin: 4
    general: 5
    email: 6
  islocked:
    approved: 0
    unclaimed: 1
    claimed: 2
    newreg: 3
    invalid: 5
  names:
    org: ITBHU Global
  urls:
    claim: http://localhost:8888/home/index.html
  privacyicon:
    1: prvme.gif
    2: prvfriends.gif
    3: prvbhu.gif
    4: prvall.gif
  role:
    superadmin: 1
    admin:      2
    masterauth: 3
    auth:       4
    user:       5
    guest:      6
  authcode:
    none:       0
    classauth:  1
    otherauth:  2
    masterauth: 3