default:
  http_metas:
    content-type: text/html

  metas:
    title:        Alumni Sangam
    robots:       index, follow
    description:  Alumni Sangam Web Portal
    keywords:     Alumni Sangam, ITBHU, V2,   
    language:     en

  stylesheets:    [itbhu]

  javascripts:    []

  has_layout:     on
  layout:         layout
siteviewSuccess:
  has_layout:     on
  layout:         peplayout
